IPMVAL-3740 fix
42ity/fty-alert-engine pull request #279
Opened 2022-06-05 16:27 UTC by jeffdegott

* IPMVAL-3740: fix rule evaluation process on ADD rule
Signed-off-by: Francois-Regis Degott <FrancoisRegisDegott@eaton.com>

2022-06-09 09:25 UTC, eric3873 requested changes

2022-06-09 09:25 UTC, ericclappier-eaton commented on src/fty_alert_engine_server.cc
> +        log_debug("rule not found (name: %s)", name);
Crash if name is null, better to test it at the beginning

2022-06-09 09:25 UTC, ericclappier-eaton commented on src/fty_alert_engine_server.cc
> +    mtxAlertConfig.unlock();
maybe an issue if send_alerts is calling below when another thread delete some elements

2022-06-09 09:25 UTC, eric3873 commented on src/fty_alert_engine_server.cc
> +    assert(name);
return better

2022-06-09 09:25 UTC, eric3873 commented on src/fty_alert_engine_server.cc
> +        if (which == mlm_client_msgpipe(client)) {
else if ??

2022-06-09 09:25 UTC, ericclappier-eaton commented on src/fty_alert_engine_server.cc
> +        if (which == mlm_client_msgpipe(client)) {
else if better

2022-06-10 09:36 UTC, aquette commented on src/autoconfig.cc
> +        //TODO rewrite that crappy message processing
s/message processing/agent/
:D ;)

2022-06-10 09:38 UTC, aquette commented on src/fty_alert_engine.cc
> +    log_info("%s started", ENGINE_AGENT_NAME);
should be alert_engine_name (even if should be the same)

2022-06-10 09:38 UTC, aquette commented on src/fty_alert_engine.cc
> +        log_debug("%s: recv msg '%s'", ENGINE_AGENT_NAME, msg);
ditto above...

2022-06-10 09:40 UTC, aquette commented on src/fty_alert_engine_server.cc
> +    mtxAlertConfig.unlock();
to be mutexed so

2022-06-10 09:41 UTC, aquette approved these changes
LGTM as long as @eric3873 's comments are addressed!

2022-06-10 10:07 UTC, jeffdegott commented on src/fty_alert_engine_server.cc
> +    mtxAlertConfig.unlock();
reverted

2022-06-10 11:40 UTC, jeffdegott commented on src/fty_alert_engine_server.cc
> +    mtxAlertConfig.unlock();
viewed with Eric. All is ok  ;)

2022-06-10 11:41 UTC, eric3873 approved these changes

2022-06-13 08:34 UTC, merged